title: NLP4CALL
description: Workshop on Natural Language Processing for Computer Assisted Language Learning
show_downloads: false
google_analytics: true
theme: jekyll-theme-slate
github:
  is_project_page: false #to remove "view on GitHub" badge

collections:
  people:
    output: true
  editions:

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "people"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

baseurl : "/NLP4CALL" # does not include hostname
