title: NLP4CALL
description: Workshop on Natural Language Processing for Computer Assisted Language Learning
show_downloads: false
google_analytics: true
theme: jekyll-theme-slate
github:
  is_project_page: false #to remove "view on GitHub" badge

collections:
  people:
    output: true
  editions:

excerpt_separator: <!--end_excerpt-->

defaults:
  - scope:
      path: ""
      type: "people"
    values:
      layout: "people"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

#baseurl : "/current" # does not include hostname

include:
- _pages

safe: false

plugins:
  - jekyll-datapage-generator

page_gen-dirs: true # uncomment, if you prefer to generate named folders

page_gen:
  - data: 'editions'
    template: 'editions'
    name: 'year'
    dir: 'past_editions'
    title: "long_name"
    title_expr: nil.to_s+"NLP4CALL ".to_s+record["year"].to_s
